### PR TITLE
Suggestions for the README

### PR DESCRIPTION
**Pull request by maelvls**
Hi,

Your first draw of `README` is great! 

I looked at the `README` on https://github.com/boostorg/compute; I found it also really inspiring! This PR contains some suggestions "copied" from Boost.Compute.

Regards,

Maël

### CODE REVIEW

**Comment by murraycu** [comment]
Thanks.

You removed the links to the list of open and closed bugs. I'd really like to keep them because it's otherwise very hard to get to these lists.

Boost Graph is not a headers-only library, though it almost is. Therefore it does not seem wise to tell people to "build" only the headers.

I doubt that the README should mention -std=c++11. I don't think it's required, though I wish it was.

**Comment by murraycu** [comment]
About the text that discusses trac versus the Issue Tracker, it would be simpler to just keep the current text and link to the mailing list decision from the "GitHub issue tracker is not (yet) used" text.

**Comment by maelvls** [comment]
Hi! Thanks for your insight on that patch! So here is what I tried to fix:
- Re-added the closed/open issues link. You are right, it's not easy to "get" to trac, it's a good idea to keep the links around
- Rephrased the "BGL is mostly made of headers": you are right, the `libboost_graph` contains functions `read_graphviz_new.cpp` and `graphml.cpp` (mostly readers for external formats).
- Removed the mention to `-std=c++11`

For the text about trac versus others, I didn't find the right "authoritative" link to the Boost Dev mailing-list archive. Here are the three I found:
- [Google Groups archive](https://groups.google.com/forum/#!searchin/boost-devel-archive/issue$20tracker/boost-devel-archive/b9SRc8LwJhA/Ok_HkKQvHroJ) (easy to browse with `subject:[graph]` search)
- [Nabble archive](http://boost.2283326.n4.nabble.com/Master-project-GitHub-issues-disabled-td4674622.html) (also easy to browse with `subject:graph`, but search results less readable)
- [GMane archive](http://thread.gmane.org/gmane.comp.lib.boost.devel/259349/) (pain to browse)
- [Official archive](http://lists.boost.org/Archives/boost/2015/04/221665.php) (horrible to browse)

Which link should we give?

**Comment by murraycu** [comment]
I think you should use the official link, however horrible it is, please.

**Comment by murraycu** [comment]
Thanks. Do you mind if I squash all your commits and my commits for this into one commit, mentioning you in the commit message? It's not fair to make the maintainer review all the steps we took to get the one file.

**Comment by maelvls** [comment]
Sure, as you wish!

**Pull request merged**
